# Typically, the root of the project folder contains
# a src folder for the .py source code files,
# a tests folder for unit tests, and
# a docs folder for any documentation
# (such as those generated by the Sphinx documentation tool).
#
# Other files contain project information and tool configuration:
# README.md for general information,
# .coveragerc for code coverage configuration,
# LICENSE.txt for the project’s software license, and so on.
#
# you can use the cookiecutter Python module to create these files and folders automatically.
# You’ll find the full documentation for both the module and the Cookiecutter command line program at
# https://cookiecutter.readthedocs.io/.

# TODO: More to learn
